version: '3'

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-orevan-blog
        ports:
            - "51153:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: php-orevan-blog
        ports:
            - "9001:9000"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel

    mysql:
        image: mysql:5.7.22
        container_name: mysql-orevan-blog
        restart: unless-stopped
        tty: true
        ports:
            - "3333:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: orevan-blog
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-orevan-blog
        depends_on:
            - mysql
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            PMA_POSRT: 3333
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel
